language: ruby
services:
  - mysql
  - postgresql
before_install:
  - gem update --system
  - gem --version
rvm:
  - 2.6.8
  - 2.7.4
  - 3.0.2
gemfile:
  - gemfiles/rails52.gemfile
  - gemfiles/rails60.gemfile
  - gemfiles/rails61.gemfile
script:
  - "bin/test"
matrix:
  fast_finish: true
bundler_args: --jobs 3 --retry 3
