language: ruby
before_install:
  - gem install bundler
before_script:
  - mysql -e 'create database fresh_connection_test;'
  - mysql -e 'create database fresh_connection_test_master;'
  - mysql -e 'create database fresh_connection_test_slave;'
  - bundle update
cache: bundler
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails50.gemfile
  fast_finish: true
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
notifications:
  emails:
    - tsukasa.oishi@gmail.com
bundler_args: --jobs 3 --retry 3
