language: ruby
services:
  - mysql
  - postgresql
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
gemfile:
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
script:
  - "bin/test"
matrix:
  fast_finish: true
bundler_args: --jobs 3 --retry 3
