language: ruby
services:
  - mysql
  - postgresql
before_install:
  - gem update --system
  - gem --version
rvm:
  - 2.6.9
  - 2.7.5
  - 3.0.3
gemfile:
  - gemfiles/rails52.gemfile
  - gemfiles/rails60.gemfile
  - gemfiles/rails61.gemfile
script:
  - "bin/test"
matrix:
  fast_finish: true
  exclude:
    - rvm: 3.0.3
      gemfile: gemfiles/rails52.gemfile

bundler_args: --jobs 3 --retry 3
